---
title: "Valores Faltantes"
author: "Mauricio Carrillo"
date: "1/5/2022"
output: html_document
---

#### Cargando datos

```{r}
housing.data <- read.csv("C:/Users/LUIS 1/Desktop/MachineLearningR/data/t1/housing-with-missing-value.csv", header = TRUE, stringsAsFactors = FALSE)
summary(housing.data)
str(housing.data)
head(housing.data)
```




#### ELiminar todas las observaciones que contengan algún NA

```{r}
housing.data.1 <- na.omit(housing.data)
summary(housing.data.1)
```


#### Eliminar las NAs de ciertas columnas

```{r}
drop_na <- c("rad")
housing.data.2 <- housing.data[ 
  complete.cases(housing.data[,!(names(housing.data))%in% drop_na]),]

summary(housing.data.2)
```


#### Eliminar toda una columna

```{r}
housing.data$rad <- NULL
summary(housing.data)

drops <- c("rad", "ptratio")
housing.data.3 <- housing.data[,!(names(housing.data) %in% drops)]
summary(housing.data.3)
```

```{r}
library(Hmisc)

housing.data.copy1 <- housing.data
housing.data.copy1$ptratio <- impute(housing.data.copy1$ptratio, mean)
housing.data.copy1$rad <- impute(housing.data.copy1$rad, mean)
summary(housing.data.copy1)

housing.data.copy2 <- housing.data
housing.data.copy2$ptratio <- impute(housing.data.copy2$ptratio, median)
housing.data.copy2$rad <- impute(housing.data.copy2$rad, median)
summary(housing.data.copy2)

housing.data.copy3 <- housing.data
housing.data.copy3$ptratio <- impute(housing.data.copy3$ptratio, 18)
housing.data.copy3$rad <- impute(housing.data.copy3$rad, 7)
summary(housing.data.copy3)

```


```{r}

library(mice)
md.pattern(housing.data)

library(VIM)

aggr(housing.data,
     col= c('green', 'red'),
     numbers = TRUE, 
     sortVars = TRUE,
     labels = names(housing.data),
     cex.axis = 0.75,
     gap = 1,
     ylab = c("Histograma de NAs", "Patrón")
)   
```
  
